version: '3.9'

services:
  frontend:
    build:
      dockerfile: "./docker/dev/Dockerfile"
      context: "./"

    container_name: "ig-frontend"

    env_file:
      - ./.env

    ports:
      - "3000:3000"

    volumes:
      - /app/node_modules
      - ./:/app
